"""Generate the LVGL bitmap fonts for the GIGA dashboard from Windows' Bahnschrift.

Bahnschrift is Microsoft's DIN 1451 and ships as a variable font. This script cuts
static instances with fontTools, then converts them with lv_font_conv (via npx).

Output: Dashboard/src/fonts/*.c plus Dashboard/src/fonts/fonts.h

The generated .c files contain glyph bitmaps derived from a Microsoft font. They are
for use on this personal device only; do not publish them.

Usage:  python tools/build_fonts.py
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "Dashboard" / "src" / "fonts"
SOURCE = Path(os.environ.get("WINDIR", r"C:\Windows")) / "Fonts" / "bahnschrift.ttf"
LV_FONT_CONV = "lv_font_conv@1.5.3"

DIGITS = "0123456789"
# Printable ASCII, German letters and the few typographic marks the UI uses.
TEXT_RANGES = ["0x20-0x7E", "0xA0", "0xB0", "0xB7", "0xC4", "0xD6", "0xDC", "0xDF",
               "0xE4", "0xF6", "0xFC", "0xD7", "0x2013", "0x2014", "0x2022", "0x2026",
               "0x2039", "0x203A", "0x201E", "0x201C"]
# Song titles and artists (now playing): all of Latin-1 and Latin Extended-A plus common
# punctuation. bridge/media.py keeps only these characters - keep both lists in sync.
MEDIA_RANGES = ["0x20-0x7E", "0xA0-0xFF", "0x100-0x17F", "0x2010-0x2014", "0x2018-0x201E",
                "0x2020-0x2022", "0x2026", "0x2030", "0x2039", "0x203A", "0x20AC", "0x2122"]

# name: (weight, width, size, ranges-or-symbols)
INSTANCES = {
    "cond_semibold": (600, 75),
    "semilight": (350, 100),
    "semicond_regular": (400, 87.5),
    "semicond_semibold": (600, 87.5),
}

FONTS = [
    # Display role: condensed semibold numerals
    ("font_time_120", "cond_semibold", 120, {"symbols": DIGITS + ":-"}),
    ("font_num_48", "cond_semibold", 48, {"symbols": DIGITS + ":°–-."}),
    ("font_num_40", "cond_semibold", 40, {"symbols": DIGITS + "°–-.%"}),
    # Body role: semilight, full width
    ("font_title_34", "semilight", 34, {"ranges": TEXT_RANGES}),
    ("font_body_24", "semilight", 24, {"ranges": TEXT_RANGES}),
    # Utility role: semicondensed for hints, now playing and labels
    ("font_ui_22", "semicond_regular", 22, {"ranges": MEDIA_RANGES}),
    ("font_label_18", "semicond_semibold", 18, {"ranges": TEXT_RANGES}),
]


def make_instance(name: str, wght: float, wdth: float, out: Path) -> Path:
    path = out / f"bahnschrift_{name}.ttf"
    if path.exists():
        return path
    font = TTFont(SOURCE)
    static = instancer.instantiateVariableFont(font, {"wght": wght, "wdth": wdth})
    static.save(path)
    return path


def convert(font_name: str, ttf: Path, size: int, spec: dict) -> None:
    out_file = OUT_DIR / f"{font_name}.c"
    cmd = ["npx", "-y", LV_FONT_CONV, "--font", str(ttf)]
    if "symbols" in spec:
        cmd += ["--symbols", spec["symbols"]]
    for r in spec.get("ranges", []):
        cmd += ["-r", r]
    cmd += ["--size", str(size), "--bpp", "4", "--format", "lvgl", "--no-compress",
            "--lv-include", "lvgl.h", "--lv-font-name", font_name, "-o", str(out_file)]
    print(f"  {font_name}: {ttf.name} @ {size}px")
    subprocess.run(cmd, check=True, shell=(os.name == "nt"))


def write_header() -> None:
    lines = ["// Generated by tools/build_fonts.py - do not edit.",
             "#pragma once", '#include "lvgl.h"', "",
             "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    for name, *_ in FONTS:
        lines.append(f"LV_FONT_DECLARE({name});")
    lines += ["", "#ifdef __cplusplus", "}", "#endif", ""]
    (OUT_DIR / "fonts.h").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if not SOURCE.exists():
        print(f"Bahnschrift not found at {SOURCE}", file=sys.stderr)
        return 1
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    cache = Path(tempfile.gettempdir()) / "giga_dashboard_fonts"
    cache.mkdir(exist_ok=True)
    print("Cutting static instances ...")
    ttfs = {k: make_instance(k, w, wd, cache) for k, (w, wd) in INSTANCES.items()}
    print("Converting ...")
    for font_name, inst, size, spec in FONTS:
        convert(font_name, ttfs[inst], size, spec)
    write_header()
    print(f"Done: {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
